### ISSUE TITLE
VRInitError_Init_HmdNotFoundPresenceFailed

### ISSUE THREAD

**Issue by rsmeers** [KonqiTheKonqueror/Source2-PFSK#6] opened 2020-06-05 21:34 UTC
Greetings,

I bought the game and installed Source2-PFSK so I could try and create content. I did add "-novr" to the launch options, but still, I can't launch the game because of a popup that says "SteamVR failed initialization with error code VRInitError_Init_HmdNotFoundPresenceFailed: Hmd Not Found Presence Failed (126). Please verify SteamVR is properly installed and try again".

I don't have an HMD. Is there a way I can get through this popup, nonetheless?

Thank you

**Comment by KonqiTheKonqueror** [comment] 2020-06-05 23:19
Hello, 

This issue is a duplicate of #5, please verify the Half-Life: Alyx workshop tools are installed and try again. If this does not work, open the Half-Life: Alyx Workshop Tools and uncheck "Enable VR".

**Closed** 2020-06-05 23:20 UTC
Labels: duplicate, game issue, invalid
